### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by dylex** [addam/polygonization#1]
```
  File "svg2polygon.py", line 93, in svg_to_lists
    for x, y in ntuples(args, 2):
  File "svg2polygon.py", line 10, in ntuples
    for i in xrange(l//n):
```
Changing this to `range` seems to work?

**Comment by addam** [comment]
Replacing `xrange` with `range` is perfectly okay. This script was written for Python 2, so this is an archaism than a mistyped letter.
